const header = document.querySelector(".header")
const toggle = document.querySelector(".toggle-button")
const rateButton = document.querySelector(".rate-button")
const modal = document.querySelector(".modal")
const btnModalClose = document.querySelector(".modal__close")
const companionsFilter = document.querySelectorAll(".companions-filter__fieldset")
const locationFilter = document.querySelector(".location-filter")
const locationFilterLands = document.querySelector(".location-filter-lands")
const btnCloseLocationFilter = document.querySelector(".location-filter__button")
const 